### PR TITLE
Initial implementation for local test execution

### PR DESCRIPTION
**Pull request by kKdH**

### CODE REVIEW

**Comment by kKdH** [comment]
Hey @LenaJok and @Derrezed-Fez, i drafted this PR, so we have place to discuss your changes. Of course it is currently in very early stage, but i already have some comments.

- Please fix your git config and set the correct author name and email address. see [here](https://api.eclipse.org/git/eca/status/gh/eclipse-opendut/opendut/123)
  After that you can re-write the history (e.g. with an interactive rebase) and force push to the `test-executor` branch.
- Also update your branch with the latest changes of the `development` branch, so the `test-executor` branch has a chance to pass the build at all.

Thank you very much for your contribution!

**Comment by LenaJok** [comment]
> Hey @LenaJok and @Derrezed-Fez, i drafted this PR, so we have place to discuss your changes. Of course it is currently in very early stage, but i already have some comments.
> 
> * Please fix your git config and set the correct author name and email address. see [here](https://api.eclipse.org/git/eca/status/gh/eclipse-opendut/opendut/123)
>   After that you can re-write the history (e.g. with an interactive rebase) and force push to the `test-executor` branch.
> * Also update your branch with the latest changes of the `development` branch, so the `test-executor` branch has a chance to pass the build at all.
> 
> Thank you very much for your contribution!

Hi @kKdH thank you for your message. I addressed your comments.

**Comment by LenaJok** [comment]
@kKdH  It was brought to my attention that you or somebody else on the team is working on creating test execution engine. Is that connected with this story, Test Execution in which we are working on creating Docker and Python Environment managers?

I am happy to discuss that topic and learn more about the work that is planned for that.

Thank you!

**Comment by voelkera** [comment]
Hi @LenaJok yes it is kind of connected, but it focuses on getting infos that are needed to start a container (e.g. image, environment variables, ports to publish) from the user to EDGAR. 

The implementation includes the possibility to define container specifics via LEA or CLEO and for EDGAR to get them from CARL when the service is started.  

You can find the container specifications we are making configurable in the according ticket #54. For now we are only focusing on containers, but will also make it possible to define scripts later. Also at the moment we are not yet focusing on the Test Execution and are doing more of an exploration to see how we can execute somehting on EDGAR.

**Comment by voelkera** [comment]
Hey @LenaJok , can you give us a quick update on your current status of the test executor?

**Comment by LenaJok** [comment]
> Hey @LenaJok , can you give us a quick update on your current status of the test executor?

Hi @voelkera we now have a detailed plan on how to extend existent rudimentary implementation of the test executor and will implement that in upcoming weeks. I was thinking of closing this pull request and branch and starting from the fresh branch as our understanding of what needs to be implemented and how has changed.

**Comment by LenaJok** [comment]
I am closing this issue as our plan is different than what was implemented here.

**Pull request closed without merging**
